### ISSUE TITLE
Babel self-transpilation

### ISSUE THREAD

**Issue by buckelieg** [jarslab/babel-maven-plugin#10]
Whenever I have babel js amongst other js files in included sources it tries to transpile itself and then fails.

> Failed on Babel transpile execution. javax.script.ScriptException: ReferenceError: "console" is not defined in <eval> at line number 2 at column number 28539

Suggest to exclude "babelSrc" file be default

Upd. : it fails with the same message on arbitrary script :( 
Babel 6.26.0

**Comment by milpol** [comment]
I'm not sure whether I catch it right, do you mean you have included babel sources twice?

**Comment by milpol** [comment]
Closing because of no response, please ping me if that's still valid, thanks
