### ISSUE TITLE
Plugin fails with babel 7.8.3

### ISSUE THREAD

**Issue by ktor** [jarslab/babel-maven-plugin#13]
Plugin v1.3 fails with message

> Failed on Babel transpile execution. Failed on Babel transpile execution.: java.lang.RuntimeException: javax.script.ScriptException: ReferenceError: "Symbol" is not defined in <eval> at line number 6189

I suppose that Babael 7.8.3 does not include Symbol polyfill which is needed to be addressed during build process.

What versions of babel do you currently support ?

**Comment by ktor** [comment]
Ok, I've found it. Plugin only works with https://registry.npmjs.org/babel-standalone/-/babel-standalone-6.26.0.tgz. Since 7.x it misses polyfills for nashorn.
https://github.com/babel/babel/issues/7607

**Comment by milpol** [comment]
I will try out GraalVM as a Nashorn replacement, it should address this issue.

**Comment by milpol** [comment]
Current master works on GraalVM + Babel 7.8.4 in tests, I will smear this implementation with some love and push new version to central.

**Comment by milpol** [comment]
It didn't work, sorry :( it run into CL issue. 
Current master should be good though, I check it on external project.

**Comment by milpol** [comment]
Fix available in version `1.4`.

**Comment by ktor** [comment]
Version 1.4 works flawlessly with @babel/standalone 7.8.7, thank you @milpol !

**Comment by milpol** [comment]
Great to hear, thanks!
