### ISSUE TITLE
Presets with options

### ISSUE THREAD

**Issue by samuei** [jarslab/babel-maven-plugin#18]
From what I've read, babel presets since 6.13 can have options, e.g.

`{
  "presets": [
    [ "es2015", { "modules": false } ]
  ]
}`

Is there a way to pass these options through this plugin? It seems like plugin is parsing the preset string with `.split(',')`, which would keep that from being an option.

**Comment by milpol** [comment]
Valid point. To keep backward compatibility I added the `formatPresets` option which (once set to `false`) disables the formatting.
Changes are available from version `1.6`.

**Comment by samuei** [comment]
Awesome!
