### ISSUE TITLE
Q: how exactly it works?

### ISSUE THREAD

**Issue by php-coder** [jarslab/babel-maven-plugin#2]
Hi,

thank you for the plugin!

I'm definitely going to try it but I don't understand how it works. I see that the plugin executes JS code with ScriptEngine (Nashhorn as far I understand):

https://github.com/jarslab/babel-maven-plugin/blob/1a8920f2255fe40f80aa65b18c17c2e090e2a282/src/main/java/com/jarslab/maven/babel/plugin/BabelTranspiler.java#L20

But it's not clear from where `Babel.transform()` function is came from. The plugin doesn't have dependency on babel webjar and there is no recommendation that I should include it either.

Could you, please, explain this moment and perhaps document it?

Thank you!

**Comment by php-coder** [comment]
Ah, I found it:

> babelSrc - readable path to standalone(!) Babel sources. It can be provided from WebJars dependency, minified or development version,

**Comment by php-coder** [comment]
P.S. Perhaps, README.md could be updated to show the example of using it with WebJars? Just an idea.

**Comment by milpol** [comment]
Hi!

you are right, documentation needs some love, I already received couple of
emails asking for help...
Please check my other project: https://github.com/milpol/onefold it uses
complete Maven front end bundling, it should answer your question.
Let me know if that helped

Thanks!
Milosz
