### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by santosh20290** [jarslab/babel-maven-plugin#22]
[ERROR] Failed to execute goal com.jarslab.maven:babel-maven-plugin:1.4:babel (js-transpile) on project test1: Failed on Babel transpile execution.: java.util.concurrent.CompletionException: java.lang.RuntimeException: org.graalvm.polyglot.PolyglotException: RangeError: Maximum call stack size exceeded 

I am getting above error while. I have 178 total JS files

**Comment by milpol** [comment]
Hi @santosh20290 are you sure it's about the number of JS files? (`PolyglotException` is only an source exception carrier).
What if you narrow the number of JS files? Does it pass?

**Comment by santosh20290** [comment]
Hi @milpol 
Thanks for your time
issue resolved it was javascript code error in some files.
Happy Coding!!!!!
