### ISSUE TITLE
How Can I minify output files

### ISSUE THREAD

**Issue by remes2000** [jarslab/babel-maven-plugin#24]
Hi, thanks for this great tool :) 
My problem is I don't know how to force this plugin/babel to produce minified files. Do You have any ideas about how to accomplish this?

**Comment by milpol** [comment]
Hi, thanks! 
The plugin itself can't do such thing, but it can be combined with other tools.
Check the example project: https://github.com/milpol/onefold
Also you can rely on recent @ktor answer on StackOverflow: https://stackoverflow.com/questions/45126476/how-to-configure-mvn-to-download-a-npm-dependency#answer-62168578
