### ISSUE TITLE
Babel fails with "empty range in char class"

### ISSUE THREAD

**Issue by php-coder** [jarslab/babel-maven-plugin#5]
Here the exception that I got:

> [ERROR] Failed to execute goal com.jarslab.maven:babel-maven-plugin:1.0:babel (default-cli) on project mystamps: Failed on Babel transpile execution.: javax.script.ScriptException: SyntaxError: empty range in char class in <eval> at line number 6 -> [Help 1]

It happens because I run this under Windows:
```console
$ mvn -X babel:babel 2>&1 | grep -i encoding
Default locale: en_GB, platform encoding: Cp1252
```

This is the same error as described there: https://stackoverflow.com/questions/32972054/empty-range-in-char-class-in-eval-when-trying-to-run-browser-js-on-nashorn

It seems like the plugin could specify file encoding explicitly or make it configurable.

At this moment, I used the following workaround: `JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8 mvn babel:babel`

**Comment by milpol** [comment]
Good catch, thank you.
Currently I don't have any Win machine, so my issue reproduction was somewhat artificial, but, as far as I understood root cause setting encoding (instead of using system default) should do the magic.
There will be new parameter `encoding`, available in version 1.2.
