### ISSUE TITLE
Plugin fails with babel 7.6.4

### ISSUE THREAD

**Issue by buckelieg** [jarslab/babel-maven-plugin#8]
Plugin fails with message 

> Failed on Babel transpile execution. java.lang.RuntimeException: javax.script.ScriptException: ReferenceError: "WeakMap" is not defined in <eval> at line number

I suppose that Babael 7.6.4 does not include WeakMap polyfill which is needed to be addressed during build process.
It would be nice to have an option to configure babel execution runtime in plugin configuration

**Comment by ktor** [comment]
The plugin only works with https://registry.npmjs.org/babel-standalone/-/babel-standalone-6.26.0.tgz. Since 7.x it misses polyfills for nashorn.
https://github.com/babel/babel/issues/7607

**Comment by milpol** [comment]
Please check current master (no bundle yet).

**Comment by ktor** [comment]
@buckelieg, version 1.4 works flawlessly with @babel/standalone 7.8.7
